spring:
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 1111
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
dubbo:
  registry:
    address: zookeeper://10.188.180.3:2181?init.timeout=200000
    timeout: 500000
  metadata-report:
    address: zookeeper://10.188.180.3:2181?init.timeout=200000
  application:
    name: dubbo-demo
  provider:
    group: rongbao-dev
    timeout: 50000
    retries: 3
  consumer:
    group: rongbao-dev
    timeout: 500000
  protocol:
    port: 20881
    name: dubbo
  scan:
    base-packages: com.jack.learn.dubbo
  config-center:
    timeout: 20000